# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('fechac_ingreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_vida', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admini.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaLaborando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admini.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='GradosCursados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GradosEducativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grados_educativos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Depto')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_f', models.CharField(blank=True, max_length=9, null=True)),
                ('telefono_c', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.EstadoCivil')),
                ('grados_cursados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.GradosCursados')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencia', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParentezco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parentezco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_organizativa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Residencia'),
        ),
        migrations.AddField(
            model_name='personas',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Sexo'),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_sangre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.TipoSangre'),
        ),
        migrations.AddField(
            model_name='personas',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradoscursados',
            name='grados_educativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.GradosEducativos'),
        ),
        migrations.AddField(
            model_name='gradoscursados',
            name='nivel_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.NivelAcademico'),
        ),
        migrations.AddField(
            model_name='familialaborando',
            name='persona',
            field=models.ManyToManyField(to='admini.Personas'),
        ),
        migrations.AddField(
            model_name='familiacolaborador',
            name='persona',
            field=models.ManyToManyField(to='admini.Personas'),
        ),
        migrations.AddField(
            model_name='depto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Pais'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='admini.Personas'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='persona_refirio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonaReferida', to='admini.Personas'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='unidad_organizativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.UnidadOrganizativa'),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='colaborador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admini.Colaborador'),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='persona',
            field=models.ManyToManyField(to='admini.Personas'),
        ),
    ]
