# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_auto_20170925_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='admini.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codFinca', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fincaLote', models.CharField(blank=True, max_length=100, null=True)),
                ('toneladasReales', models.FloatField()),
                ('distancia', models.FloatField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Comunidad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.EstadoFinca')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codLote', models.IntegerField()),
                ('comunidad', models.ManyToManyField(to='admini.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidadFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comunidad_Final', to='admini.Comunidad')),
                ('comunidadInicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comunidad_Inicio', to='admini.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCosecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaCosecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='finca',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Lote'),
        ),
        migrations.AddField(
            model_name='finca',
            name='sistemaCosecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.SistemaCosecha'),
        ),
        migrations.AddField(
            model_name='finca',
            name='tenencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tenencia', to='admini.Tenencia'),
        ),
        migrations.AddField(
            model_name='finca',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zona_o_Distrito', to='admini.Zona'),
        ),
    ]
