# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0003_auto_20171023_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbasAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='finca',
            name='fincaLote',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='cant_h',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunidad',
            name='cant_m',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenencia',
            name='hnton',
            field=models.FloatField(default=20.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunidad',
            name='agua',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Abastecimiento_Agua', to='admini.AbasAgua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunidad',
            name='des',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tiene_Escuela', to='admini.Descicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunidad',
            name='tipo_comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Comunidad', to='admini.TipoComunidad'),
            preserve_default=False,
        ),
    ]
