# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0004_auto_20171031_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='cant_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='cant_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
