# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0005_auto_20171101_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenencia',
            name='hnton',
        ),
        migrations.AddField(
            model_name='finca',
            name='hnton',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
