# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0006_auto_20171101_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priorizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Comunidad')),
                ('criterio', models.ManyToManyField(to='admini.Criterio')),
            ],
        ),
        migrations.AlterField(
            model_name='finca',
            name='hnton',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
