# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0007_auto_20171102_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='agua',
        ),
        migrations.DeleteModel(
            name='AbasAgua',
        ),
    ]
