# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0009_auto_20171102_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='cant_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
