# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0010_comunidad_cant_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
