# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0011_comunidad_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='agua',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='agua',
            field=models.ManyToManyField(related_name='Abastecimiento_Agua', to='admini.AbasAgua'),
        ),
    ]
