# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0012_auto_20171120_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='toneladas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
