# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0013_comunidad_toneladas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='toneladas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
