# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0014_auto_20171121_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priorizar',
            old_name='valor',
            new_name='valoragua',
        ),
        migrations.RemoveField(
            model_name='priorizar',
            name='criterio',
        ),
        migrations.AddField(
            model_name='priorizar',
            name='valorpi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priorizar',
            name='valorproce',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priorizar',
            name='valorqmi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priorizar',
            name='valorruta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priorizar',
            name='valortone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
