# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0016_auto_20171121_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorizar',
            name='valoragua',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priorizar',
            name='valorpi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priorizar',
            name='valorproce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priorizar',
            name='valorqmi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priorizar',
            name='valorruta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priorizar',
            name='valortone',
            field=models.IntegerField(null=True),
        ),
    ]
