# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0017_auto_20171121_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorizar',
            name='comunidad',
        ),
        migrations.DeleteModel(
            name='Priorizar',
        ),
    ]
