# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0019_priorizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorizar',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
