# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0020_priorizar_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorizar',
            name='total',
        ),
    ]
