# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0022_priorizar_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='escuela',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admini.Descicion'),
            preserve_default=False,
        ),
    ]
