# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0025_comunidad_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zafra', models.CharField(max_length=100)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='priorizar',
            name='capa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admini.Capa'),
            preserve_default=False,
        ),
    ]
