# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0027_auto_20171130_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Comunidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='priorizar',
            name='total',
        ),
    ]
