# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0028_auto_20171130_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
