# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0029_auto_20171130_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='des',
        ),
    ]
