# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0030_remove_comunidad_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='capa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admini.Capa'),
            preserve_default=False,
        ),
    ]
