# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0031_resultados_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
