# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0032_auto_20171130_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultados',
            name='capa',
        ),
        migrations.AddField(
            model_name='resultados',
            name='criterios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admini.Priorizar'),
            preserve_default=False,
        ),
    ]
