# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0035_auto_20171201_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
