# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0036_auto_20171201_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoQuema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quema', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='ton_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='ton_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='tipo_quema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admini.TipoQuema'),
            preserve_default=False,
        ),
    ]
