# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0037_auto_20171203_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='ton_total',
        ),
    ]
