# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0038_remove_comunidad_ton_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='tipo_quema',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='ha',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='ton_ha',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
