# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0040_comunidad_tipo_quema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='tipo_quema',
        ),
    ]
