# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0041_remove_comunidad_tipo_quema'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='tipo_quema',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='admini.TipoQuema'),
        ),
    ]
