# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0042_comunidad_tipo_quema'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='pi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Productores', to='admini.Descicion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Procedencia', to='admini.Descicion'),
        ),
    ]
