# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0043_auto_20171204_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='ton_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
