# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0044_comunidad_ton_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='ha',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='ton_ha',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
